defaults:
  - custom_ray_aws

ray:
  cluster:
    docker:
      run_options:
        - --gpus all
        - --mount type=bind,source="$(pwd)/disk1/${outputs_dir}",target=/workspace/${outputs_dir}
        - --mount type=bind,source="$(pwd)/disk1/${datasets_dir}",target=/workspace/${datasets_dir}

    available_node_types:
      ray.head.default:
        node_config:
          InstanceType: g4dn.xlarge

    initialization_commands:
      - sudo mkfs -t ext4 /dev/nvme1n1
      - mkdir disk1
      - sudo mount /dev/nvme1n1 disk1
      - sudo chown -R ec2-user disk1
      - mkdir -p disk1/${outputs_dir}
      - mkdir -p disk1/${datasets_dir}
