cluster_name: p3.8xlarge_ray

max_workers: 0

idle_timeout_minutes: 5

docker:
  image: lucasbignone/stylegan3_ray:0.5
  container_name: stylegan3_ray
  run_options:
    - --gpus all
    - --mount type=bind,source="$(pwd)/disk1/outputs",target=/workspace/outputs  #  mount a persistent location for outputs
    - --mount type=bind,source="$(pwd)/disk1/multirun",target=/workspace/multirun
    - --mount type=bind,source="$(pwd)/disk1/datasets",target=/workspace/datasets  #  mount a persistent location for datasets

provider:
  type: aws
  region: us-east-1
  cache_stopped_nodes: False

auth:
    ssh_user: ec2-user

available_node_types:
  ray.head.default:
    resources: {}
    node_config:
      InstanceType: p3.8xlarge
      ImageId: ami-0e9d3c53b79c2cc6f  # Deep Learning AMI GPU CUDA 11.4.3 (Amazon Linux 2) 20220316
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 250
            VolumeType: gp3

initialization_commands:
  - mkdir disk1
  - mkdir -p disk1/outputs  #  output location
  - mkdir -p disk1/multirun  #  output location
  - mkdir -p disk1/datasets  #  datasets location
#  - aws s3 cp s3://innova-conicet-imaging-datasets/galaxies/eagle_galrand_64x64.zip disk1/datasets/.

#setup_commands:
#  - screen -S sync_outputs -d -m python watch_and_sync_to_s3.py outputs s3://innova-conicet-output
#  - screen -S sync_multirun -d -m python watch_and_sync_to_s3.py multirun s3://innova-conicet-output

file_mounts: {
  "/workspace": "./",  # upload current directory to the docker working directory
}
